# Generated by Django 3.1.4 on 2020-12-23 09:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('indexcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcheck',
            name='comment',
            field=models.TextField(blank=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='indexcheck',
            name='code',
            field=django_mysql.models.ListCharField(models.CharField(max_length=255, verbose_name='コード'), max_length=15, size=None),
        ),
    ]
